version: '3'
services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
    env_file:
      - 'env.influxdb'
    volumes:
      # Data persistency
      # sudo mkdir -p /tmp/docker/influxdb/data
      - /tmp/docker/influxdb/data:/var/lib/influxdb

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    env_file:
      - 'env.grafana'
    links:
      - influxdb
    volumes:
      # Data persistency
      # sudo mkdir -p /tmp/docker/grafana/data; chown 472:472 /tmp/docker/grafana/data
      - /tmp/docker/grafana/data:/var/lib/grafana

  system-monitor:
    image: kyoungho/telegraf:latest
    container_name: system-monitor
    links:
      - influxdb
    volumes:
      - ./system_monitor.conf:/app/telegraf.conf:ro

  dds-monitor:
    image: kyoungho/telegraf:latest
    container_name: dds-monitor
    volumes:
      - ./dds_monitor.conf:/app/telegraf.conf:ro

  system-collector:
    image: kyoungho/telegraf:latest
    container_name: system-collector
    environment:
      HOST_PROC: /rootfs/proc
      HOST_SYS: /rootfs/sys
      HOST_ETC: /rootfs/etc
    volumes:
      - ./system_collector.conf:/app/telegraf.conf:ro
      - /sys:/rootfs/sys:ro
      - /proc:/rootfs/proc:ro
      - /etc:/rootfs/etc:ro
    privileged: true
    pid: host
    network_mode: host

  bat-sim:
    image: bat-sim
    container_name: bat-sim

  bat-control:
    image: bat-control
    container_name: bat-control
