version: '3'
services:
  telegraf:
    image: kyoungho/telegraf:latest
    container_name: telegraf
    environment:
      HOST_PROC: /rootfs/proc
      HOST_SYS: /rootfs/sys
      HOST_ETC: /rootfs/etc
    volumes:
      - ./system_to_ddslp.conf:/app/telegraf.conf:ro
      - /sys:/rootfs/sys:ro
      - /proc:/rootfs/proc:ro
      - /etc:/rootfs/etc:ro
    privileged: true
    pid: host
    network_mode: host

  routing-service:
    image: rti-routingservice:latest
    container_name: rti-routingservice
    ports:
      - "7400:7400"
    env_file:
      - 'env.rs'
    volumes:
      - ./routing_service.xml:/app/config.xml:ro
